name: deploy

on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types:
        completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build & deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-client
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: jetli/wasm-pack-action@v0.3.0

      - run: npm ci
      - run: npm run build

      - name: Copying files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "./web-client/dist"
          target: ${{ secrets.REMOTE_DIR }}
